services:
  - type: web
    name: licence-api
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && python app.py
    envVars:
      - key: DB_TYPE
        value: mysql
      - key: MYSQL_HOST
        value: 108.179.252.54
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_DATABASE
        value: scpmtc84_api
      - key: MYSQL_USER
        value: scpmtc84_api
      - key: MYSQL_PASSWORD
        value: nQT-8gW%-qCY
      - key: PYTHON_VERSION
        value: 3.11.0

